openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: lesson 2
servers:
  - url: /v1
paths:
  /accounts:
    post:
      description: Create Account
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        '201':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    get:
      description: Customer Id
      operationId: accounts/queryAccounts
      parameters:
        - in: query
          name: customerId
          schema:
            type: integer
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'


  /accounts/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      description: Get balance.
      operationId: getBalance
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    Account:
      type: object
      properties:
        balance:
          type: integer
        id:
          type: integer
        label:
          type: string
        type:
          type: string
          enum:
            - checking
            - savings    